package com.bank.entity;
// Generated 11-may-2019 10:49:08 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkBenBeneficiary generated by hbm2java
 */
@Entity
@Table(name = "bnk_ben_beneficiary", schema = "beneficiary")
public class BnkBenBeneficiary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int benCode;
	private String benUsrcod;
	private String benName;
	private String benAccount;
	private String benType;
	private String benEmail;
	private String benStatus;
	private String benCreatedBy;
	private Date benCreatedDate;
	private String benModifiedBy;
	private Date benModifiedDate;

	public BnkBenBeneficiary() {
	}

	public BnkBenBeneficiary(int benCode, String benUsrcod, String benName, String benAccount, String benCreatedBy,
			Date benCreatedDate) {
		this.benCode = benCode;
		this.benUsrcod = benUsrcod;
		this.benName = benName;
		this.benAccount = benAccount;
		this.benCreatedBy = benCreatedBy;
		this.benCreatedDate = benCreatedDate;
	}

	public BnkBenBeneficiary(int benCode, String benUsrcod, String benName, String benAccount, String benType,
			String benEmail, String benStatus, String benCreatedBy, Date benCreatedDate, String benModifiedBy,
			Date benModifiedDate) {
		this.benCode = benCode;
		this.benUsrcod = benUsrcod;
		this.benName = benName;
		this.benAccount = benAccount;
		this.benType = benType;
		this.benEmail = benEmail;
		this.benStatus = benStatus;
		this.benCreatedBy = benCreatedBy;
		this.benCreatedDate = benCreatedDate;
		this.benModifiedBy = benModifiedBy;
		this.benModifiedDate = benModifiedDate;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ben_code", unique = true, nullable = false, length = 10)
	public int getBenCode() {
		return this.benCode;
	}

	public void setBenCode(int benCode) {
		this.benCode = benCode;
	}

	@Column(name = "ben_usrcod", nullable = false, length = 10)
	public String getBenUsrcod() {
		return this.benUsrcod;
	}

	public void setBenUsrcod(String benUsrcod) {
		this.benUsrcod = benUsrcod;
	}

	@Column(name = "ben_name", nullable = false, length = 50)
	public String getBenName() {
		return this.benName;
	}

	public void setBenName(String benName) {
		this.benName = benName;
	}

	@Column(name = "ben_account", nullable = false, length = 10)
	public String getBenAccount() {
		return this.benAccount;
	}

	public void setBenAccount(String benAccount) {
		this.benAccount = benAccount;
	}

	@Column(name = "ben_type", length = 5)
	public String getBenType() {
		return this.benType;
	}

	public void setBenType(String benType) {
		this.benType = benType;
	}

	@Column(name = "ben_email", length = 30)
	public String getBenEmail() {
		return this.benEmail;
	}

	public void setBenEmail(String benEmail) {
		this.benEmail = benEmail;
	}

	@Column(name = "ben_status", length = 1)
	public String getBenStatus() {
		return this.benStatus;
	}

	public void setBenStatus(String benStatus) {
		this.benStatus = benStatus;
	}

	@Column(name = "ben_created_by", nullable = false, length = 25)
	public String getBenCreatedBy() {
		return this.benCreatedBy;
	}

	public void setBenCreatedBy(String benCreatedBy) {
		this.benCreatedBy = benCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ben_created_date", nullable = false, length = 29)
	public Date getBenCreatedDate() {
		return this.benCreatedDate;
	}

	public void setBenCreatedDate(Date benCreatedDate) {
		this.benCreatedDate = benCreatedDate;
	}

	@Column(name = "ben_modified_by", length = 25)
	public String getBenModifiedBy() {
		return this.benModifiedBy;
	}

	public void setBenModifiedBy(String benModifiedBy) {
		this.benModifiedBy = benModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ben_modified_date", length = 29)
	public Date getBenModifiedDate() {
		return this.benModifiedDate;
	}

	public void setBenModifiedDate(Date benModifiedDate) {
		this.benModifiedDate = benModifiedDate;
	}

}
