server:
  port: 2000
    
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank?currentSchema=users #cambiar puerto.
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
service:
  configuration:
    http:
      http-request-timeout: 90000
      socket-timeout: 90000
      conn-request-timeout: 90000
      max-threads: 400
      max-threads-per-route: 200    
logging:
  level:
    org:
      springframework:
        web: WARN
  path: file-log/
  file: ${logging.path}bank-product-svc
  maxHistory: 30
  
  
config:
  format: dd-MMM-yyyy
  data:
    loan: LoanDatabase
    card: CardDatabase
    acc: AccDatabase
    tra: TransactionService
  endpoints:
    accounts: getAccounts
    transfer:
      own: ownTransfer
      third: thirdTransfer
    payment:
      own-card: ownPayCard
      third-card: thirdPayCard
      own-loan: ownPayLoan
      third-loan: thirdPayLoan
    loan: getInfoLoan/{usr}/{id}
    card: getInfoCard/{usr}/{id}
    account: getInfoAcc/{usr}/{id}
    loan-id: getInfoLoan/{id}
    card-id: getInfoCard/{id}
    account-id: getInfoAcc/{id}
    svc:
      transaction-svc:
        save: http://localhost:2001/transaction