package com.bank.entity;
// Generated 10-may-2019 9:13:31 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkUsrUser generated by hbm2java
 */
@Entity
@Table(name = "bnk_usr_user", schema = "users")
public class BnkUsrUser implements java.io.Serializable {

	private String usrCode;
	private String usrPwd;
	private BigDecimal usrTries;
	private String usrStatus;
	private Date usrLastLoginDate;
	private String usrCreatedBy;
	private Date usrCreatedDate;
	private String usrModifiedBy;
	private Date usrModifiedDate;

	public BnkUsrUser() {
	}

	public BnkUsrUser(String usrCode, String usrPwd, String usrCreatedBy, Date usrCreatedDate) {
		this.usrCode = usrCode;
		this.usrPwd = usrPwd;
		this.usrCreatedBy = usrCreatedBy;
		this.usrCreatedDate = usrCreatedDate;
	}

	public BnkUsrUser(String usrCode, String usrPwd, BigDecimal usrTries, String usrStatus, Date usrLastLoginDate,
			String usrCreatedBy, Date usrCreatedDate, String usrModifiedBy, Date usrModifiedDate) {
		this.usrCode = usrCode;
		this.usrPwd = usrPwd;
		this.usrTries = usrTries;
		this.usrStatus = usrStatus;
		this.usrLastLoginDate = usrLastLoginDate;
		this.usrCreatedBy = usrCreatedBy;
		this.usrCreatedDate = usrCreatedDate;
		this.usrModifiedBy = usrModifiedBy;
		this.usrModifiedDate = usrModifiedDate;
	}

	@Id

	@Column(name = "usr_code", unique = true, nullable = false, length = 10)
	public String getUsrCode() {
		return this.usrCode;
	}

	public void setUsrCode(String usrCode) {
		this.usrCode = usrCode;
	}

	@Column(name = "usr_pwd", nullable = false, length = 200)
	public String getUsrPwd() {
		return this.usrPwd;
	}

	public void setUsrPwd(String usrPwd) {
		this.usrPwd = usrPwd;
	}

	@Column(name = "usr_tries", precision = 131089, scale = 0)
	public BigDecimal getUsrTries() {
		return this.usrTries;
	}

	public void setUsrTries(BigDecimal usrTries) {
		this.usrTries = usrTries;
	}

	@Column(name = "usr_status", length = 1)
	public String getUsrStatus() {
		return this.usrStatus;
	}

	public void setUsrStatus(String usrStatus) {
		this.usrStatus = usrStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "usr_last_login_date", length = 13)
	public Date getUsrLastLoginDate() {
		return this.usrLastLoginDate;
	}

	public void setUsrLastLoginDate(Date usrLastLoginDate) {
		this.usrLastLoginDate = usrLastLoginDate;
	}

	@Column(name = "usr_created_by", nullable = false, length = 25)
	public String getUsrCreatedBy() {
		return this.usrCreatedBy;
	}

	public void setUsrCreatedBy(String usrCreatedBy) {
		this.usrCreatedBy = usrCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_created_date", nullable = false, length = 29)
	public Date getUsrCreatedDate() {
		return this.usrCreatedDate;
	}

	public void setUsrCreatedDate(Date usrCreatedDate) {
		this.usrCreatedDate = usrCreatedDate;
	}

	@Column(name = "usr_modified_by", length = 25)
	public String getUsrModifiedBy() {
		return this.usrModifiedBy;
	}

	public void setUsrModifiedBy(String usrModifiedBy) {
		this.usrModifiedBy = usrModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_modified_date", length = 29)
	public Date getUsrModifiedDate() {
		return this.usrModifiedDate;
	}

	public void setUsrModifiedDate(Date usrModifiedDate) {
		this.usrModifiedDate = usrModifiedDate;
	}

}
