package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkAxuAccountUser generated by hbm2java
 */
@Entity
@Table(name = "bnk_axu_account_user", schema = "products")
public class BnkAxuAccountUser implements java.io.Serializable {

	private String axuCode;
	private BnkAccAccount bnkAccAccount;
	private String axuUsrcod;
	private BigDecimal axuBalance;
	private String axuStatus;
	private String axuCreatedBy;
	private Date axuCreatedDate;
	private String axuModifiedBy;
	private Date axuModifiedDate;

	public BnkAxuAccountUser() {
	}

	public BnkAxuAccountUser(String axuCode, BnkAccAccount bnkAccAccount, String axuUsrcod, String axuStatus,
			String axuCreatedBy, Date axuCreatedDate) {
		this.axuCode = axuCode;
		this.bnkAccAccount = bnkAccAccount;
		this.axuUsrcod = axuUsrcod;
		this.axuStatus = axuStatus;
		this.axuCreatedBy = axuCreatedBy;
		this.axuCreatedDate = axuCreatedDate;
	}

	public BnkAxuAccountUser(String axuCode, BnkAccAccount bnkAccAccount, String axuUsrcod, BigDecimal axuBalance,
			String axuStatus, String axuCreatedBy, Date axuCreatedDate, String axuModifiedBy, Date axuModifiedDate) {
		this.axuCode = axuCode;
		this.bnkAccAccount = bnkAccAccount;
		this.axuUsrcod = axuUsrcod;
		this.axuBalance = axuBalance;
		this.axuStatus = axuStatus;
		this.axuCreatedBy = axuCreatedBy;
		this.axuCreatedDate = axuCreatedDate;
		this.axuModifiedBy = axuModifiedBy;
		this.axuModifiedDate = axuModifiedDate;
	}

	@Id

	@Column(name = "axu_code", unique = true, nullable = false, length = 10)
	public String getAxuCode() {
		return this.axuCode;
	}

	public void setAxuCode(String axuCode) {
		this.axuCode = axuCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "axu_acccod", nullable = false)
	public BnkAccAccount getBnkAccAccount() {
		return this.bnkAccAccount;
	}

	public void setBnkAccAccount(BnkAccAccount bnkAccAccount) {
		this.bnkAccAccount = bnkAccAccount;
	}

	@Column(name = "axu_usrcod", nullable = false, length = 25)
	public String getAxuUsrcod() {
		return this.axuUsrcod;
	}

	public void setAxuUsrcod(String axuUsrcod) {
		this.axuUsrcod = axuUsrcod;
	}

	@Column(name = "axu_balance", precision = 131089, scale = 0)
	public BigDecimal getAxuBalance() {
		return this.axuBalance;
	}

	public void setAxuBalance(BigDecimal axuBalance) {
		this.axuBalance = axuBalance;
	}

	@Column(name = "axu_status", nullable = false, length = 1)
	public String getAxuStatus() {
		return this.axuStatus;
	}

	public void setAxuStatus(String axuStatus) {
		this.axuStatus = axuStatus;
	}

	@Column(name = "axu_created_by", nullable = false, length = 25)
	public String getAxuCreatedBy() {
		return this.axuCreatedBy;
	}

	public void setAxuCreatedBy(String axuCreatedBy) {
		this.axuCreatedBy = axuCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "axu_created_date", nullable = false, length = 29)
	public Date getAxuCreatedDate() {
		return this.axuCreatedDate;
	}

	public void setAxuCreatedDate(Date axuCreatedDate) {
		this.axuCreatedDate = axuCreatedDate;
	}

	@Column(name = "axu_modified_by", length = 25)
	public String getAxuModifiedBy() {
		return this.axuModifiedBy;
	}

	public void setAxuModifiedBy(String axuModifiedBy) {
		this.axuModifiedBy = axuModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "axu_modified_date", length = 29)
	public Date getAxuModifiedDate() {
		return this.axuModifiedDate;
	}

	public void setAxuModifiedDate(Date axuModifiedDate) {
		this.axuModifiedDate = axuModifiedDate;
	}

}
