package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkAccAccount generated by hbm2java
 */
@Entity
@Table(name = "bnk_acc_account", schema = "products")
public class BnkAccAccount implements java.io.Serializable {

	private String accCode;
	private String accName;
	private String accDescription;
	private String accCreatedBy;
	private Date accCreatedDate;
	private String accModifiedBy;
	private Date accModifiedDate;
	private Set<BnkAxuAccountUser> bnkAxuAccountUsers = new HashSet<BnkAxuAccountUser>(0);

	public BnkAccAccount() {
	}

	public BnkAccAccount(String accCode, String accName, String accCreatedBy, Date accCreatedDate) {
		this.accCode = accCode;
		this.accName = accName;
		this.accCreatedBy = accCreatedBy;
		this.accCreatedDate = accCreatedDate;
	}

	public BnkAccAccount(String accCode, String accName, String accDescription, String accCreatedBy,
			Date accCreatedDate, String accModifiedBy, Date accModifiedDate,
			Set<BnkAxuAccountUser> bnkAxuAccountUsers) {
		this.accCode = accCode;
		this.accName = accName;
		this.accDescription = accDescription;
		this.accCreatedBy = accCreatedBy;
		this.accCreatedDate = accCreatedDate;
		this.accModifiedBy = accModifiedBy;
		this.accModifiedDate = accModifiedDate;
		this.bnkAxuAccountUsers = bnkAxuAccountUsers;
	}

	@Id

	@Column(name = "acc_code", unique = true, nullable = false, length = 6)
	public String getAccCode() {
		return this.accCode;
	}

	public void setAccCode(String accCode) {
		this.accCode = accCode;
	}

	@Column(name = "acc_name", nullable = false, length = 25)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "acc_description", length = 100)
	public String getAccDescription() {
		return this.accDescription;
	}

	public void setAccDescription(String accDescription) {
		this.accDescription = accDescription;
	}

	@Column(name = "acc_created_by", nullable = false, length = 25)
	public String getAccCreatedBy() {
		return this.accCreatedBy;
	}

	public void setAccCreatedBy(String accCreatedBy) {
		this.accCreatedBy = accCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acc_created_date", nullable = false, length = 29)
	public Date getAccCreatedDate() {
		return this.accCreatedDate;
	}

	public void setAccCreatedDate(Date accCreatedDate) {
		this.accCreatedDate = accCreatedDate;
	}

	@Column(name = "acc_modified_by", length = 25)
	public String getAccModifiedBy() {
		return this.accModifiedBy;
	}

	public void setAccModifiedBy(String accModifiedBy) {
		this.accModifiedBy = accModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acc_modified_date", length = 29)
	public Date getAccModifiedDate() {
		return this.accModifiedDate;
	}

	public void setAccModifiedDate(Date accModifiedDate) {
		this.accModifiedDate = accModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bnkAccAccount")
	public Set<BnkAxuAccountUser> getBnkAxuAccountUsers() {
		return this.bnkAxuAccountUsers;
	}

	public void setBnkAxuAccountUsers(Set<BnkAxuAccountUser> bnkAxuAccountUsers) {
		this.bnkAxuAccountUsers = bnkAxuAccountUsers;
	}

}
