package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkCxuCardUser generated by hbm2java
 */
@Entity
@Table(name = "bnk_cxu_card_user", schema = "products")
public class BnkCxuCardUser implements java.io.Serializable {

	private String cxuCode;
	private BnkCrdCard bnkCrdCard;
	private String cxuUsrcod;
	private BigDecimal cxuLimit;
	private BigDecimal cxuAvailable;
	private BigDecimal cxuInterestRate;
	private BigDecimal cxuInterestAmount;
	private Integer cxuMonthlyCut;
	private String cxuStatus;
	private String cxuCreatedBy;
	private Date cxuCreatedDate;
	private String cxuModifiedBy;
	private Date cxuModifiedDate;

	public BnkCxuCardUser() {
	}

	public BnkCxuCardUser(String cxuCode, BnkCrdCard bnkCrdCard, String cxuUsrcod, String cxuStatus,
			String cxuCreatedBy, Date cxuCreatedDate) {
		this.cxuCode = cxuCode;
		this.bnkCrdCard = bnkCrdCard;
		this.cxuUsrcod = cxuUsrcod;
		this.cxuStatus = cxuStatus;
		this.cxuCreatedBy = cxuCreatedBy;
		this.cxuCreatedDate = cxuCreatedDate;
	}

	public BnkCxuCardUser(String cxuCode, BnkCrdCard bnkCrdCard, String cxuUsrcod, BigDecimal cxuLimit,
			BigDecimal cxuAvailable, BigDecimal cxuInterestRate, BigDecimal cxuInterestAmount, Integer cxuMonthlyCut,
			String cxuStatus, String cxuCreatedBy, Date cxuCreatedDate, String cxuModifiedBy, Date cxuModifiedDate) {
		this.cxuCode = cxuCode;
		this.bnkCrdCard = bnkCrdCard;
		this.cxuUsrcod = cxuUsrcod;
		this.cxuLimit = cxuLimit;
		this.cxuAvailable = cxuAvailable;
		this.cxuInterestRate = cxuInterestRate;
		this.cxuInterestAmount = cxuInterestAmount;
		this.cxuMonthlyCut = cxuMonthlyCut;
		this.cxuStatus = cxuStatus;
		this.cxuCreatedBy = cxuCreatedBy;
		this.cxuCreatedDate = cxuCreatedDate;
		this.cxuModifiedBy = cxuModifiedBy;
		this.cxuModifiedDate = cxuModifiedDate;
	}

	@Id

	@Column(name = "cxu_code", unique = true, nullable = false, length = 10)
	public String getCxuCode() {
		return this.cxuCode;
	}

	public void setCxuCode(String cxuCode) {
		this.cxuCode = cxuCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cxu_crdcod", nullable = false)
	public BnkCrdCard getBnkCrdCard() {
		return this.bnkCrdCard;
	}

	public void setBnkCrdCard(BnkCrdCard bnkCrdCard) {
		this.bnkCrdCard = bnkCrdCard;
	}

	@Column(name = "cxu_usrcod", nullable = false, length = 25)
	public String getCxuUsrcod() {
		return this.cxuUsrcod;
	}

	public void setCxuUsrcod(String cxuUsrcod) {
		this.cxuUsrcod = cxuUsrcod;
	}

	@Column(name = "cxu_limit", precision = 131089, scale = 0)
	public BigDecimal getCxuLimit() {
		return this.cxuLimit;
	}

	public void setCxuLimit(BigDecimal cxuLimit) {
		this.cxuLimit = cxuLimit;
	}

	@Column(name = "cxu_available", precision = 131089, scale = 0)
	public BigDecimal getCxuAvailable() {
		return this.cxuAvailable;
	}

	public void setCxuAvailable(BigDecimal cxuAvailable) {
		this.cxuAvailable = cxuAvailable;
	}

	@Column(name = "cxu_interest_rate", precision = 131089, scale = 0)
	public BigDecimal getCxuInterestRate() {
		return this.cxuInterestRate;
	}

	public void setCxuInterestRate(BigDecimal cxuInterestRate) {
		this.cxuInterestRate = cxuInterestRate;
	}

	@Column(name = "cxu_interest_amount", precision = 131089, scale = 0)
	public BigDecimal getCxuInterestAmount() {
		return this.cxuInterestAmount;
	}

	public void setCxuInterestAmount(BigDecimal cxuInterestAmount) {
		this.cxuInterestAmount = cxuInterestAmount;
	}

	@Column(name = "cxu_monthly_cut")
	public Integer getCxuMonthlyCut() {
		return this.cxuMonthlyCut;
	}

	public void setCxuMonthlyCut(Integer cxuMonthlyCut) {
		this.cxuMonthlyCut = cxuMonthlyCut;
	}

	@Column(name = "cxu_status", nullable = false, length = 1)
	public String getCxuStatus() {
		return this.cxuStatus;
	}

	public void setCxuStatus(String cxuStatus) {
		this.cxuStatus = cxuStatus;
	}

	@Column(name = "cxu_created_by", nullable = false, length = 25)
	public String getCxuCreatedBy() {
		return this.cxuCreatedBy;
	}

	public void setCxuCreatedBy(String cxuCreatedBy) {
		this.cxuCreatedBy = cxuCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cxu_created_date", nullable = false, length = 29)
	public Date getCxuCreatedDate() {
		return this.cxuCreatedDate;
	}

	public void setCxuCreatedDate(Date cxuCreatedDate) {
		this.cxuCreatedDate = cxuCreatedDate;
	}

	@Column(name = "cxu_modified_by", length = 25)
	public String getCxuModifiedBy() {
		return this.cxuModifiedBy;
	}

	public void setCxuModifiedBy(String cxuModifiedBy) {
		this.cxuModifiedBy = cxuModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cxu_modified_date", length = 29)
	public Date getCxuModifiedDate() {
		return this.cxuModifiedDate;
	}

	public void setCxuModifiedDate(Date cxuModifiedDate) {
		this.cxuModifiedDate = cxuModifiedDate;
	}

}
