package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkCrdCard generated by hbm2java
 */
@Entity
@Table(name = "bnk_crd_card", schema = "products")
public class BnkCrdCard implements java.io.Serializable {

	private String crdCode;
	private String crdName;
	private String crdDescription;
	private String crdCreatedBy;
	private Date crdCreatedDate;
	private String crdModifiedBy;
	private Date crdModifiedDate;
	private Set<BnkCxuCardUser> bnkCxuCardUsers = new HashSet<BnkCxuCardUser>(0);

	public BnkCrdCard() {
	}

	public BnkCrdCard(String crdCode, String crdName, String crdCreatedBy, Date crdCreatedDate) {
		this.crdCode = crdCode;
		this.crdName = crdName;
		this.crdCreatedBy = crdCreatedBy;
		this.crdCreatedDate = crdCreatedDate;
	}

	public BnkCrdCard(String crdCode, String crdName, String crdDescription, String crdCreatedBy, Date crdCreatedDate,
			String crdModifiedBy, Date crdModifiedDate, Set<BnkCxuCardUser> bnkCxuCardUsers) {
		this.crdCode = crdCode;
		this.crdName = crdName;
		this.crdDescription = crdDescription;
		this.crdCreatedBy = crdCreatedBy;
		this.crdCreatedDate = crdCreatedDate;
		this.crdModifiedBy = crdModifiedBy;
		this.crdModifiedDate = crdModifiedDate;
		this.bnkCxuCardUsers = bnkCxuCardUsers;
	}

	@Id

	@Column(name = "crd_code", unique = true, nullable = false, length = 6)
	public String getCrdCode() {
		return this.crdCode;
	}

	public void setCrdCode(String crdCode) {
		this.crdCode = crdCode;
	}

	@Column(name = "crd_name", nullable = false, length = 25)
	public String getCrdName() {
		return this.crdName;
	}

	public void setCrdName(String crdName) {
		this.crdName = crdName;
	}

	@Column(name = "crd_description", length = 100)
	public String getCrdDescription() {
		return this.crdDescription;
	}

	public void setCrdDescription(String crdDescription) {
		this.crdDescription = crdDescription;
	}

	@Column(name = "crd_created_by", nullable = false, length = 25)
	public String getCrdCreatedBy() {
		return this.crdCreatedBy;
	}

	public void setCrdCreatedBy(String crdCreatedBy) {
		this.crdCreatedBy = crdCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crd_created_date", nullable = false, length = 29)
	public Date getCrdCreatedDate() {
		return this.crdCreatedDate;
	}

	public void setCrdCreatedDate(Date crdCreatedDate) {
		this.crdCreatedDate = crdCreatedDate;
	}

	@Column(name = "crd_modified_by", length = 25)
	public String getCrdModifiedBy() {
		return this.crdModifiedBy;
	}

	public void setCrdModifiedBy(String crdModifiedBy) {
		this.crdModifiedBy = crdModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crd_modified_date", length = 29)
	public Date getCrdModifiedDate() {
		return this.crdModifiedDate;
	}

	public void setCrdModifiedDate(Date crdModifiedDate) {
		this.crdModifiedDate = crdModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bnkCrdCard")
	public Set<BnkCxuCardUser> getBnkCxuCardUsers() {
		return this.bnkCxuCardUsers;
	}

	public void setBnkCxuCardUsers(Set<BnkCxuCardUser> bnkCxuCardUsers) {
		this.bnkCxuCardUsers = bnkCxuCardUsers;
	}

}
