package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkLoaLoan generated by hbm2java
 */
@Entity
@Table(name = "bnk_loa_loan", schema = "products")
public class BnkLoaLoan implements java.io.Serializable {

	private String loaCode;
	private String loaName;
	private String loaDescription;
	private String loaCreatedBy;
	private Date loaCreatedDate;
	private String loaModifiedBy;
	private Date loaModifiedDate;
	private Set<BnkLxuLoanUser> bnkLxuLoanUsers = new HashSet<BnkLxuLoanUser>(0);

	public BnkLoaLoan() {
	}

	public BnkLoaLoan(String loaCode, String loaName, String loaCreatedBy, Date loaCreatedDate) {
		this.loaCode = loaCode;
		this.loaName = loaName;
		this.loaCreatedBy = loaCreatedBy;
		this.loaCreatedDate = loaCreatedDate;
	}

	public BnkLoaLoan(String loaCode, String loaName, String loaDescription, String loaCreatedBy, Date loaCreatedDate,
			String loaModifiedBy, Date loaModifiedDate, Set<BnkLxuLoanUser> bnkLxuLoanUsers) {
		this.loaCode = loaCode;
		this.loaName = loaName;
		this.loaDescription = loaDescription;
		this.loaCreatedBy = loaCreatedBy;
		this.loaCreatedDate = loaCreatedDate;
		this.loaModifiedBy = loaModifiedBy;
		this.loaModifiedDate = loaModifiedDate;
		this.bnkLxuLoanUsers = bnkLxuLoanUsers;
	}

	@Id

	@Column(name = "loa_code", unique = true, nullable = false, length = 6)
	public String getLoaCode() {
		return this.loaCode;
	}

	public void setLoaCode(String loaCode) {
		this.loaCode = loaCode;
	}

	@Column(name = "loa_name", nullable = false, length = 25)
	public String getLoaName() {
		return this.loaName;
	}

	public void setLoaName(String loaName) {
		this.loaName = loaName;
	}

	@Column(name = "loa_description", length = 100)
	public String getLoaDescription() {
		return this.loaDescription;
	}

	public void setLoaDescription(String loaDescription) {
		this.loaDescription = loaDescription;
	}

	@Column(name = "loa_created_by", nullable = false, length = 25)
	public String getLoaCreatedBy() {
		return this.loaCreatedBy;
	}

	public void setLoaCreatedBy(String loaCreatedBy) {
		this.loaCreatedBy = loaCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loa_created_date", nullable = false, length = 29)
	public Date getLoaCreatedDate() {
		return this.loaCreatedDate;
	}

	public void setLoaCreatedDate(Date loaCreatedDate) {
		this.loaCreatedDate = loaCreatedDate;
	}

	@Column(name = "loa_modified_by", length = 25)
	public String getLoaModifiedBy() {
		return this.loaModifiedBy;
	}

	public void setLoaModifiedBy(String loaModifiedBy) {
		this.loaModifiedBy = loaModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loa_modified_date", length = 29)
	public Date getLoaModifiedDate() {
		return this.loaModifiedDate;
	}

	public void setLoaModifiedDate(Date loaModifiedDate) {
		this.loaModifiedDate = loaModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bnkLoaLoan")
	public Set<BnkLxuLoanUser> getBnkLxuLoanUsers() {
		return this.bnkLxuLoanUsers;
	}

	public void setBnkLxuLoanUsers(Set<BnkLxuLoanUser> bnkLxuLoanUsers) {
		this.bnkLxuLoanUsers = bnkLxuLoanUsers;
	}

}
