package com.bank.entity;
// Generated 10-may-2019 16:34:51 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BnkLxuLoanUser generated by hbm2java
 */
@Entity
@Table(name = "bnk_lxu_loan_user", schema = "products")
public class BnkLxuLoanUser implements java.io.Serializable {

	private String lxuCode;
	private BnkLoaLoan bnkLoaLoan;
	private String lxuUsrcod;
	private BigDecimal lxuTotal;
	private BigDecimal lxuDebt;
	private BigDecimal lxuInterestRate;
	private BigDecimal lxuInterestAmount;
	private String lxuStatus;
	private String lxuCreatedBy;
	private Date lxuCreatedDate;
	private String lxuModifiedBy;
	private Date lxuModifiedDate;

	public BnkLxuLoanUser() {
	}

	public BnkLxuLoanUser(String lxuCode, BnkLoaLoan bnkLoaLoan, String lxuUsrcod, String lxuStatus,
			String lxuCreatedBy, Date lxuCreatedDate) {
		this.lxuCode = lxuCode;
		this.bnkLoaLoan = bnkLoaLoan;
		this.lxuUsrcod = lxuUsrcod;
		this.lxuStatus = lxuStatus;
		this.lxuCreatedBy = lxuCreatedBy;
		this.lxuCreatedDate = lxuCreatedDate;
	}

	public BnkLxuLoanUser(String lxuCode, BnkLoaLoan bnkLoaLoan, String lxuUsrcod, BigDecimal lxuTotal,
			BigDecimal lxuDebt, BigDecimal lxuInterestRate, BigDecimal lxuInterestAmount, String lxuStatus,
			String lxuCreatedBy, Date lxuCreatedDate, String lxuModifiedBy, Date lxuModifiedDate) {
		this.lxuCode = lxuCode;
		this.bnkLoaLoan = bnkLoaLoan;
		this.lxuUsrcod = lxuUsrcod;
		this.lxuTotal = lxuTotal;
		this.lxuDebt = lxuDebt;
		this.lxuInterestRate = lxuInterestRate;
		this.lxuInterestAmount = lxuInterestAmount;
		this.lxuStatus = lxuStatus;
		this.lxuCreatedBy = lxuCreatedBy;
		this.lxuCreatedDate = lxuCreatedDate;
		this.lxuModifiedBy = lxuModifiedBy;
		this.lxuModifiedDate = lxuModifiedDate;
	}

	@Id

	@Column(name = "lxu_code", unique = true, nullable = false, length = 10)
	public String getLxuCode() {
		return this.lxuCode;
	}

	public void setLxuCode(String lxuCode) {
		this.lxuCode = lxuCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lxu_loacod", nullable = false)
	public BnkLoaLoan getBnkLoaLoan() {
		return this.bnkLoaLoan;
	}

	public void setBnkLoaLoan(BnkLoaLoan bnkLoaLoan) {
		this.bnkLoaLoan = bnkLoaLoan;
	}

	@Column(name = "lxu_usrcod", nullable = false, length = 25)
	public String getLxuUsrcod() {
		return this.lxuUsrcod;
	}

	public void setLxuUsrcod(String lxuUsrcod) {
		this.lxuUsrcod = lxuUsrcod;
	}

	@Column(name = "lxu_total", precision = 131089, scale = 0)
	public BigDecimal getLxuTotal() {
		return this.lxuTotal;
	}

	public void setLxuTotal(BigDecimal lxuTotal) {
		this.lxuTotal = lxuTotal;
	}

	@Column(name = "lxu_debt", precision = 131089, scale = 0)
	public BigDecimal getLxuDebt() {
		return this.lxuDebt;
	}

	public void setLxuDebt(BigDecimal lxuDebt) {
		this.lxuDebt = lxuDebt;
	}

	@Column(name = "lxu_interest_rate", precision = 131089, scale = 0)
	public BigDecimal getLxuInterestRate() {
		return this.lxuInterestRate;
	}

	public void setLxuInterestRate(BigDecimal lxuInterestRate) {
		this.lxuInterestRate = lxuInterestRate;
	}

	@Column(name = "lxu_interest_amount", precision = 131089, scale = 0)
	public BigDecimal getLxuInterestAmount() {
		return this.lxuInterestAmount;
	}

	public void setLxuInterestAmount(BigDecimal lxuInterestAmount) {
		this.lxuInterestAmount = lxuInterestAmount;
	}

	@Column(name = "lxu_status", nullable = false, length = 1)
	public String getLxuStatus() {
		return this.lxuStatus;
	}

	public void setLxuStatus(String lxuStatus) {
		this.lxuStatus = lxuStatus;
	}

	@Column(name = "lxu_created_by", nullable = false, length = 25)
	public String getLxuCreatedBy() {
		return this.lxuCreatedBy;
	}

	public void setLxuCreatedBy(String lxuCreatedBy) {
		this.lxuCreatedBy = lxuCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lxu_created_date", nullable = false, length = 29)
	public Date getLxuCreatedDate() {
		return this.lxuCreatedDate;
	}

	public void setLxuCreatedDate(Date lxuCreatedDate) {
		this.lxuCreatedDate = lxuCreatedDate;
	}

	@Column(name = "lxu_modified_by", length = 25)
	public String getLxuModifiedBy() {
		return this.lxuModifiedBy;
	}

	public void setLxuModifiedBy(String lxuModifiedBy) {
		this.lxuModifiedBy = lxuModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lxu_modified_date", length = 29)
	public Date getLxuModifiedDate() {
		return this.lxuModifiedDate;
	}

	public void setLxuModifiedDate(Date lxuModifiedDate) {
		this.lxuModifiedDate = lxuModifiedDate;
	}

}
